resolver: lts-17.8

allow-newer: true

packages:
  - "GPipe-Core"
  - "GPipe-Engine"
  - "GPipe-Fonts"
  - "GPipe-GLFW4"
  - "lambdacnc"
  - "lambdaray"
  - "livecoding"
  - "scenegraph"
  - "th-abstraction"
  - "unordered-containers-0.2.10.0"
  - "Cabal"

extra-deps:
  - parsec-3.1.14.0@sha256:72d5c57e6e126adaa781ab97b19dc76f68490c0a3d88f14038219994cabe94e1,4356
  - text-1.2.3.2

# use custom ext-stg whole program compiler GHC
compiler: ghc-8.11.0.20200527

# use local GHC (for development)
system-ghc: true
extra-path:
  - "/home/pippijn/code/ghc-whole-program-compiler-project/ghc-wpc/_build/stage1/bin"

build:
  keep-tmp-files: true
